// src/routes/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import InvitationCover from '$lib/components/InvitationCover.svelte';
	import Navigation from '$lib/components/Navigation.svelte';
	import HeroSection from '$lib/components/HeroSection.svelte';
	import CountdownSection from '$lib/components/CountdownSection.svelte';
	import DetailsSection from '$lib/components/DetailsSection.svelte';
	import GiftSection from '$lib/components/GiftSection.svelte';
	import GallerySection from '$lib/components/GallerySection.svelte';
	import WishesSection from '$lib/components/WishesSection.svelte';
	import PhotoGallerySection from '$lib/components/PhotoGallerySection.svelte';
	import FooterSection from '$lib/components/FooterSection.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	// Cover always shows on page load
	let showCover = $state(true);
	let isHydrated = $state(false);

	/**
	 * Decodes and sanitizes guest name from URL query parameter
	 */
	function decodeGuestName(rawValue: string | null): string | undefined {
		if (!rawValue) {
			return undefined;
		}

		// Decode URL-encoded characters (handles %20, %2B, etc.)
		let decoded = decodeURIComponent(rawValue);

		// Replace + with spaces
		decoded = decoded.replace(/\+/g, ' ');

		// Trim whitespace and collapse multiple spaces to single space
		decoded = decoded.trim().replace(/\s+/g, ' ');

		// Return undefined if empty after processing
		if (!decoded) {
			return undefined;
		}

		// Validate length (max 100 characters)
		if (decoded.length > 100) {
			decoded = decoded.substring(0, 100).trim();
		}

		return decoded;
	}

	// Get guest name from server-side data, with reactive client-side updates
	const guestName = $derived.by(() => {
		// Check URL params first (for client-side navigation reactivity)
		const urlParam = $page.url.searchParams.get('to');
		if (urlParam) {
			return decodeGuestName(urlParam);
		}

		// Fallback to server-side data (for SSR initial load)
		return data.guestName;
	});

	onMount(() => {
		// Ensure body class is set for scroll lock
		document.body.classList.add('cover-active');

		// Mark as hydrated to enable smooth transitions
		isHydrated = true;

		// Ensure scroll is at top
		window.scrollTo(0, 0);
	});

	function handleOpenInvitation() {
		showCover = false;
		// Remove body class to unlock scroll
		document.body.classList.remove('cover-active');
	}
</script>

<svelte:head>
	<title>Undangan Pernikahan Alfina & Mugni</title>
	<meta
		name="description"
		content="Bergabunglah bersama kami dalam perayaan cinta Alfina dan Mugni yang memulai perjalanan baru mereka. 29 November 2025 di Jakarta, Indonesia."
	/>
	<meta property="og:title" content="Undangan Pernikahan Alfina & Mugni" />
	<meta
		property="og:description"
		content="Bergabunglah bersama kami dalam perayaan cinta Alfina dan Mugni yang memulai perjalanan baru mereka."
	/>
	<meta property="og:type" content="website" />
</svelte:head>

<!-- Invitation Cover (shows first, hides after clicking "Open Invitation") -->
{#if showCover}
	<InvitationCover {guestName} onOpen={handleOpenInvitation} />
{/if}

<!-- Main Website Content - ALWAYS rendered, initially hidden by cover -->
<div class="main-content" class:visible={!showCover} class:hydrated={isHydrated}>
	<Navigation />
	<main>
		<HeroSection />
		<CountdownSection />
		<DetailsSection />
		<GiftSection />
		<GallerySection />
		<WishesSection />
		<PhotoGallerySection />
		<FooterSection />
	</main>
</div>

<style>
	.main-content {
		opacity: 0;
		visibility: hidden;
		transition: opacity 0.5s ease-in, visibility 0s linear 0.5s;
	}

	.main-content.visible {
		opacity: 1;
		visibility: visible;
		transition: opacity 0.5s ease-in, visibility 0s linear 0s;
	}

	.main-content.hydrated.visible {
		opacity: 1;
	}
</style>

// src/routes/index.tsx
import {
  component$,
  useSignal,
  useVisibleTask$,
  useContextProvider,
  $,
} from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { useLocation } from "@builder.io/qwik-city";

import { Navigation } from "../components/navigation";
import { HeroSection } from "../components/hero-section";
import { CountdownSection } from "../components/countdown-section";
import { StorySection } from "../components/story-section";
import { DetailsSection } from "../components/details-section";
import { GiftSection } from "../components/gift-section";
import { RsvpSection } from "../components/rsvp-section";
import { WishesSection } from "../components/wishes-section";
import { GallerySection } from "../components/gallery-section";
import { ContactSection } from "../components/contact-section";
import { FooterSection } from "../components/footer-section";
import { InvitationCover } from "../components/invitation-cover";
import { AudioPlayer } from "../components/audio-player";
import { AudioContext, useAudioStore } from "../stores/audio-store";

export default component$(() => {
  const location = useLocation();
  const showCover = useSignal(true);

  // Extract guest name from URL parameter (?to=John+Doe)
  const guestName = location.url.searchParams.get("to") || undefined;

  // Initialize audio store and provide context (always, even during SSR)
  const audioStore = useAudioStore();
  useContextProvider(AudioContext, audioStore);

  // Initialize audio element on client only
  useVisibleTask$(() => {
    if (typeof window !== "undefined") {
      audioStore.init();
    }
  }, { strategy: 'document-ready' });

  // Lock body scroll when cover is visible
  useVisibleTask$(({ track }) => {
    track(() => showCover.value);

    if (typeof window !== "undefined") {
      if (showCover.value) {
        // Lock scroll when cover is visible
        document.body.style.overflow = "hidden";
        console.log("Body scroll locked");
      } else {
        // Unlock scroll when cover is hidden
        document.body.style.overflow = "";
        console.log("Body scroll unlocked");
      }
    }

    // Cleanup function to ensure scroll is restored
    return () => {
      if (typeof window !== "undefined") {
        document.body.style.overflow = "";
      }
    };
  }, { strategy: 'document-ready' });

  // Handle "Open Invitation" button click
  const handleOpenInvitation = $(() => {
    console.log("handleOpenInvitation called");
    showCover.value = false;
    // Play audio when invitation is opened
    audioStore.play();
  });

  return (
    <>
      {/* Invitation Cover (shows first, hides after clicking "Open Invitation") */}
      {showCover.value && (
        <InvitationCover
          guestName={guestName}
          onOpen$={handleOpenInvitation}
        />
      )}

      {/* Main Website Content - Only render after cover is dismissed for better performance */}
      {!showCover.value && (
        <>
          <Navigation />
          <main>
            <HeroSection />
            <CountdownSection />
            <StorySection />
            <DetailsSection />
            <GiftSection />
            <RsvpSection />
            <WishesSection />
            <GallerySection />
            <ContactSection />
            <FooterSection />
          </main>

          {/* Floating Audio Player (always visible after opening invitation) */}
          <AudioPlayer />
        </>
      )}
    </>
  );
});

export const head: DocumentHead = {
  title: "Undangan Pernikahan Alfina & Mugni",
  meta: [
    {
      name: "description",
      content:
        "Bergabunglah bersama kami dalam perayaan cinta Alfina dan Mugni yang memulai perjalanan baru mereka. 29 November 2025 di Jakarta, Indonesia.",
    },
    {
      name: "viewport",
      content: "width=device-width, initial-scale=1.0",
    },
    {
      property: "og:title",
      content: "Undangan Pernikahan Alfina & Mugni",
    },
    {
      property: "og:description",
      content:
        "Bergabunglah bersama kami dalam perayaan cinta Alfina dan Mugni yang memulai perjalanan baru mereka.",
    },
    {
      property: "og:type",
      content: "website",
    },
  ],
};
