// src/routes/g/[session_id]/+page.svelte
<script lang="ts">
	import PhotoUpload from '$lib/components/gallery/PhotoUpload.svelte';
	import PhotoGrid from '$lib/components/gallery/PhotoGrid.svelte';
	import PhotoModal from '$lib/components/gallery/PhotoModal.svelte';
	import type { PageData } from './$types';
	import { invalidateAll } from '$app/navigation';

	let { data }: { data: PageData } = $props();

	let showUploadModal = $state(false);
	let selectedPhoto = $state<any>(null);
	let showPhotoModal = $state(false);

	const transformedPhotos = $derived(
		(data.photos || []).map((p: any) => ({
			id: p.id,
			url: `/api/photos/${p.id}`,
			thumbnail: `/api/photos/${p.id}`,
			description: p.description || '',
			uploader_name: p.uploader_name || 'Anonymous',
			upload_date: p.upload_date
		}))
	);

	function handlePhotoClick(photo: any) {
		selectedPhoto = photo;
		showPhotoModal = true;
	}

	function handleCloseModal() {
		selectedPhoto = null;
		showPhotoModal = false;
	}

	async function handleUploadSuccess() {
		await invalidateAll();
	}
</script>

<svelte:head>
	<title>{data.session?.title || 'Session Gallery'} - Alfina & Mugni Wedding</title>
	<meta
		name="description"
		content={data.session?.description || 'Share photos from our wedding'}
	/>
</svelte:head>

<main class="min-h-screen bg-gradient-to-b from-wedding-cream to-white px-4 py-12">
	<div class="mx-auto max-w-7xl">
		<div class="mb-12 text-center">
			<h1 class="font-serif text-4xl font-light text-wedding-brown md:text-6xl">
				{data.session?.title || 'Session Gallery'}
			</h1>
			{#if data.session?.description}
				<p class="mt-4 text-lg text-wedding-text-muted md:text-xl">
					{data.session.description}
				</p>
			{/if}

			{#if !data.session?.is_active}
				<div
					class="mx-auto mt-6 max-w-md rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-800"
				>
					<p class="font-medium">This session is no longer accepting uploads</p>
					<p class="mt-1 text-sm">You can still view the photos below</p>
				</div>
			{/if}
		</div>

		<div class="mb-8 flex justify-center">
			<button
				type="button"
				onclick={() => (showUploadModal = true)}
				disabled={!data.session?.is_active}
				class="inline-flex items-center gap-2 rounded-lg bg-wedding-sage px-6 py-3 font-medium text-white shadow-sm transition hover:bg-wedding-sage/90 disabled:cursor-not-allowed disabled:opacity-50"
			>
				<svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
					/>
				</svg>
				{data.session?.is_active ? 'Upload Photos' : 'Uploads Closed'}
			</button>
		</div>

		<PhotoGrid photos={transformedPhotos} onPhotoClick={handlePhotoClick} />
	</div>
</main>

<PhotoUpload
	sessionId={data.session?.session_id || ''}
	isActive={data.session?.is_active ?? false}
	isOpen={showUploadModal}
	onClose={() => (showUploadModal = false)}
	onSuccess={handleUploadSuccess}
/>

<PhotoModal photo={selectedPhoto} isOpen={showPhotoModal} onClose={handleCloseModal} />

// src/routes/g/[session_id]/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import { getDatabase, type Env } from "../../../lib/database";
import { GalleryUploadSection } from "../../../components/gallery-upload-section";
import type { GalleryItem } from "../../../hooks/use-gallery";

export const useSessionGalleryData = routeLoader$(async ({ params, platform }) => {
  try {
    const sessionId = params.session_id;
    const db = getDatabase(platform.env as Env);

    // Get session
    const session = await db.getSessionBySessionId(sessionId);

    if (!session) {
      return {
        error: 'Session not found',
        session: null,
        photos: [],
      };
    }

    // Get photos for this session
    const photos = await db.getSessionPhotos(sessionId, 30);

    // Transform photos to gallery items
    const photosWithUrls = photos.map((photo) => ({
      id: photo.id?.toString() || '',
      type: 'image' as const,
      title: photo.original_name,
      description: photo.description || '',
      author: photo.uploader_name || 'Guest',
      timestamp: photo.upload_date || new Date().toISOString(),
      url: `/api/photos/${photo.id}`,
      thumbnail: `/api/photos/${photo.id}`,
      category: photo.category,
      featured: photo.featured,
    }));

    return {
      session: {
        session_id: session.session_id,
        title: session.title,
        description: session.description,
        is_active: session.is_active,
        photo_count: session.photo_count,
      },
      photos: photosWithUrls,
      error: null,
    };
  } catch (error) {
    console.error("Failed to load session gallery:", error);
    return {
      error: 'Failed to load gallery',
      session: null,
      photos: [],
    };
  }
});

export default component$(() => {
  const galleryData = useSessionGalleryData();

  if (galleryData.value.error) {
    return (
      <div class="min-h-screen flex items-center justify-center bg-wedding-cream">
        <div class="text-center">
          <h1 class="text-2xl font-semibold text-gray-900 mb-4">
            {galleryData.value.error === 'Session not found'
              ? 'Gallery Not Found'
              : 'Error Loading Gallery'}
          </h1>
          <p class="text-gray-600">
            {galleryData.value.error === 'Session not found'
              ? 'This gallery session does not exist or has been removed.'
              : 'Please try again later.'}
          </p>
        </div>
      </div>
    );
  }

  const { session, photos } = galleryData.value;

  return (
    <div class="min-h-screen bg-gradient-to-b from-white via-wedding-cream/40 to-white">
      {/* Session Header */}
      <div class="bg-white border-b border-wedding-beige">
        <div class="max-w-6xl mx-auto px-4 py-8 text-center">
          <h1 class="font-serif text-4xl font-light text-wedding-brown md:text-5xl mb-2">
            {session?.title || 'Wedding Gallery'}
          </h1>
          {session?.description && (
            <p class="text-lg text-wedding-text-muted max-w-2xl mx-auto">
              {session.description}
            </p>
          )}
          {session && (
            <div class="mt-4 flex items-center justify-center gap-4 text-sm text-gray-600">
              <span>📸 {session.photo_count} photos</span>
              {session.is_active && (
                <span class="text-green-600">🟢 Accepting uploads</span>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Gallery Component */}
      <GalleryUploadSection
        initialPhotos={photos as GalleryItem[]}
        sessionId={session?.session_id}
        isActive={session?.is_active ?? false}
      />
    </div>
  );
});

export const head: DocumentHead = ({ resolveValue }) => {
  const galleryData = resolveValue(useSessionGalleryData);
  const title = galleryData.session?.title || 'Wedding Gallery';
  
  return {
    title,
    meta: [
      {
        name: "description",
        content: galleryData.session?.description || "Share your wedding moments",
      },
    ],
  };
};
