// src/components/audio-player.tsx
import { component$, useContext, useVisibleTask$ } from "@builder.io/qwik";
import { LuMusic, LuPause, LuPlay, LuVolume2, LuVolumeX } from "@qwikest/icons/lucide";
import { AudioContext } from "~/stores/audio-store";

export const AudioPlayer = component$(() => {
  const audioStore = useContext(AudioContext);

  useVisibleTask$(() => {
    // Add keyboard support (client-only)
    if (typeof document === "undefined") return;

    const handleKeyPress = (e: KeyboardEvent) => {
      if (e.code === "Space" && e.target === document.body) {
        e.preventDefault();
        audioStore.togglePlay();
      }
      if (e.code === "KeyM") {
        audioStore.toggleMute();
      }
    };

    document.addEventListener("keydown", handleKeyPress);

    return () => {
      document.removeEventListener("keydown", handleKeyPress);
    };
  }, { strategy: 'document-ready' });

  return (
    <div
      class="audio-player-floating"
      style={{
        position: "fixed",
        bottom: "2rem",
        right: "2rem",
        zIndex: "9998",
        display: "flex",
        flexDirection: "column",
        gap: "0.5rem",
        alignItems: "flex-end",
      }}
    >
      {/* Music Bars Animation (shows when playing) */}
      {audioStore.isPlaying.value && (
        <div
          class="music-bars"
          style={{
            display: "flex",
            gap: "3px",
            alignItems: "flex-end",
            height: "20px",
            padding: "0 0.5rem",
          }}
        >
          {[0, 1, 2].map((i) => (
            <div
              key={i}
              class="music-bar"
              style={{
                width: "3px",
                backgroundColor: "var(--wedding-accent, #b2804d)",
                borderRadius: "2px",
                animation: `musicBar 0.6s ease-in-out infinite`,
                animationDelay: `${i * 0.15}s`,
                height: "100%",
                transformOrigin: "bottom",
              }}
            />
          ))}
        </div>
      )}

      {/* Main Play/Pause Button */}
      <button
        onClick$={() => audioStore.togglePlay()}
        class="audio-control-button"
        aria-label={audioStore.isPlaying.value ? "Pause music" : "Play music"}
        title={
          audioStore.isPlaying.value
            ? "Pause music (Space)"
            : "Play music (Space)"
        }
        style={{
          width: "56px",
          height: "56px",
          borderRadius: "50%",
          backgroundColor: "var(--wedding-accent, #b2804d)",
          color: "white",
          border: "2px solid white",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          cursor: "pointer",
          boxShadow: "0 4px 12px rgba(0, 0, 0, 0.3)",
          transition: "all 0.3s ease",
        }}
        onMouseEnter$={(e) => {
          (e.target as HTMLElement).style.transform = "scale(1.1)";
          (e.target as HTMLElement).style.boxShadow =
            "0 6px 16px rgba(0, 0, 0, 0.4)";
        }}
        onMouseLeave$={(e) => {
          (e.target as HTMLElement).style.transform = "scale(1)";
          (e.target as HTMLElement).style.boxShadow =
            "0 4px 12px rgba(0, 0, 0, 0.3)";
        }}
      >
        {audioStore.isPlaying.value ? (
          <LuPause class="w-6 h-6" />
        ) : (
          <LuPlay class="w-6 h-6" style={{ marginLeft: "2px" }} />
        )}
      </button>

      {/* Mute/Unmute Button (smaller) */}
      <button
        onClick$={() => audioStore.toggleMute()}
        class="audio-mute-button"
        aria-label={audioStore.isMuted.value ? "Unmute music" : "Mute music"}
        title={audioStore.isMuted.value ? "Unmute music (M)" : "Mute music (M)"}
        style={{
          width: "40px",
          height: "40px",
          borderRadius: "50%",
          backgroundColor: "white",
          color: "var(--wedding-brown, #4d3326)",
          border: "1px solid var(--wedding-beige, #f0e3d9)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          cursor: "pointer",
          boxShadow: "0 2px 8px rgba(0, 0, 0, 0.2)",
          transition: "all 0.3s ease",
        }}
        onMouseEnter$={(e) => {
          (e.target as HTMLElement).style.transform = "scale(1.1)";
        }}
        onMouseLeave$={(e) => {
          (e.target as HTMLElement).style.transform = "scale(1)";
        }}
      >
        {audioStore.isMuted.value ? (
          <LuVolumeX class="w-4 h-4" />
        ) : (
          <LuVolume2 class="w-4 h-4" />
        )}
      </button>

      {/* Now Playing Indicator (optional) */}
      {audioStore.isPlaying.value && (
        <div
          class="now-playing-text"
          style={{
            fontSize: "0.75rem",
            color: "var(--wedding-brown, #4d3326)",
            backgroundColor: "white",
            padding: "0.35rem 0.75rem",
            borderRadius: "20px",
            boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
            whiteSpace: "nowrap",
            display: "flex",
            alignItems: "center",
            gap: "0.5rem",
            maxWidth: "200px",
            animation: "fadeIn 0.3s ease-out",
          }}
        >
          <LuMusic class="w-3 h-3" />
          <span>Now Playing</span>
        </div>
      )}
    </div>
  );
});

// src/lib/components/AudioPlayer.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Pause, Play } from 'lucide-svelte';
	import { audioStore } from '$lib/stores/audioStore';
	import Toast from './Toast.svelte';

	let isPlaying = $state(false);
	let audioElement = $state<HTMLAudioElement | null>(null);
	let isHovered = $state(false);
	let wasPlayingBeforeBlur = $state(false);

	// Subscribe to audio store for autoplay trigger
	$effect(() => {
		if ($audioStore.shouldPlay && audioElement && audioElement.paused && !isPlaying) {
			play();
		}
	});

	onMount(() => {
		// Create audio element
		audioElement = new Audio('/The Wedding of Alfina & Mugni.mp3');
		audioElement.loop = true;
		audioElement.volume = 0.6;

		// Add event listeners
		audioElement.addEventListener('play', () => {
			isPlaying = true;
		});

		audioElement.addEventListener('pause', () => {
			isPlaying = false;
		});

		audioElement.addEventListener('ended', () => {
			isPlaying = false;
		});

		audioElement.addEventListener('error', (e) => {
			console.error('Audio playback error:', e);
			isPlaying = false;
		});

		// Keyboard support
		const handleKeyPress = (e: KeyboardEvent) => {
			if (e.code === 'Space' && e.target === document.body) {
				e.preventDefault();
				togglePlay();
			}
		};

		// Tab focus/blur handling - pause when tab loses focus, resume when regains focus
		const handleVisibilityChange = () => {
			if (document.hidden) {
				// Tab lost focus
				if (audioElement && !audioElement.paused) {
					wasPlayingBeforeBlur = true;
					pause();
				}
			} else {
				// Tab regained focus
				if (wasPlayingBeforeBlur && audioElement && audioElement.paused) {
					play();
					wasPlayingBeforeBlur = false;
				}
			}
		};

		document.addEventListener('keydown', handleKeyPress);
		document.addEventListener('visibilitychange', handleVisibilityChange);

		return () => {
			document.removeEventListener('keydown', handleKeyPress);
			document.removeEventListener('visibilitychange', handleVisibilityChange);
			if (audioElement) {
				audioElement.pause();
				audioElement = null;
			}
		};
	});

	async function play() {
		if (audioElement && audioElement.paused) {
			try {
				await audioElement.play();
				isPlaying = true; // Update synchronously
				audioStore.setPlaying(true);

				// Reset shouldPlay after successful autoplay to prevent effect from retriggering
				if ($audioStore.shouldPlay) {
					audioStore.resetShouldPlay();
				}
			} catch (error) {
				isPlaying = false;
				audioStore.setPlaying(false);
				audioStore.showAutoplayBlockedToast();
			}
		}
	}

	function pause() {
		if (audioElement && !audioElement.paused) {
			audioElement.pause();
			isPlaying = false; // Update synchronously
			audioStore.setPlaying(false);
		}
	}

	function togglePlay() {
		if (audioElement && !audioElement.paused) {
			pause();
		} else {
			play();
		}
	}
</script>

<div class="audio-player-floating fixed bottom-8 right-8 z-[9998] flex flex-col gap-2 items-end">
	<!-- Music Bars Animation (shows when playing) -->
	{#if isPlaying}
		<div class="music-bars flex gap-[3px] items-end h-5 px-2">
			{#each [0, 1, 2] as i}
				<div
					class="music-bar w-[3px] bg-wedding-steel rounded-sm h-full origin-bottom"
					style="animation: musicBar 0.6s ease-in-out infinite; animation-delay: {i * 0.15}s"
				/>
			{/each}
		</div>
	{/if}

	<!-- Main Play/Pause Button -->
	<button
		onclick={() => {
			togglePlay();
		}}
		onmouseenter={() => (isHovered = true)}
		onmouseleave={() => (isHovered = false)}
		class="audio-control-button w-14 h-14 rounded-full bg-wedding-steel text-white border-2 border-white flex items-center justify-center cursor-pointer shadow-[0_4px_12px_rgba(0,0,0,0.3)] transition-all duration-300"
		class:scale-110={isHovered}
		class:shadow-[0_6px_16px_rgba(0,0,0,0.4)]={isHovered}
		aria-label={isPlaying ? 'Pause music' : 'Play music'}
		title={isPlaying ? 'Pause music (Space)' : 'Play music (Space)'}
	>
		{#if isPlaying}
			<Pause class="w-6 h-6" />
		{:else}
			<Play class="w-6 h-6 ml-0.5" />
		{/if}
	</button>
</div>

<!-- Toast for autoplay blocked -->
<Toast
	message="Click play button to start music"
	show={$audioStore.showAutoplayBlockedToast}
	onDismiss={() => audioStore.hideAutoplayBlockedToast()}
/>
