// src/components/details-section.tsx
import { component$, useVisibleTask$ } from "@builder.io/qwik";
import { animateOnScroll, animateCards } from "../utils/animations";

export const DetailsSection = component$(() => {
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(() => {
    // Animate section heading
    animateOnScroll(".details-heading", { delay: 0.2, direction: "up" });

    // Animate cards with stagger
    animateCards(".details-card");
  });

  return (
    <section
      id="details"
      class="min-h-screen bg-gray-50 flex flex-col items-center justify-center px-4 py-20"
    >
      <div class="max-w-6xl mx-auto text-center">
        <h2
          class="details-heading font-serif text-4xl md:text-6xl text-wedding-brown mb-16 font-light"
          style={{ opacity: 0 }}
        >
          Detail Pernikahan
        </h2>

        <div class="grid md:grid-cols-2 gap-x-12 gap-y-8 max-w-5xl mx-auto">
          {/* Akad Nikah */}
          <div
            class="details-card wedding-card bg-wedding-beige border-0 transition-all duration-300 hover:shadow-lg"
            style={{ opacity: 0 }}
          >
            <div class="text-center p-8">
              <div class="mb-4">
                <svg
                  class="w-12 h-12 mx-auto mb-4"
                  style={{ color: "var(--wedding-accent)" }}
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path d="M10 2L3 7v11a2 2 0 002 2h4v-6h2v6h4a2 2 0 002-2V7l-7-5z"/>
                </svg>
              </div>

              <h3 class="font-serif text-3xl md:text-4xl text-wedding-brown mb-4 font-medium">
                Akad Nikah
              </h3>

              <div class="text-wedding-accent text-lg mb-4 italic">
                Upacara Akad Nikah
              </div>

              <div class="mb-6">
                <p class="text-wedding-text-secondary text-xl md:text-2xl font-medium mb-2">
                  9:00 AM - 11:30 AM
                </p>
                <p class="text-wedding-text-muted text-lg">
                  Sabtu, 29 November 2025
                </p>
              </div>

              <div class="text-wedding-text-muted text-base md:text-lg space-y-2 mb-6">
                <p class="font-medium">Tamarin Hotel Jakarta</p>
                <p>Jl. K.H. Wahid Hasyim No.77, RT.1/RW.4</p>
                <p>Gondangdia, Kec. Menteng, Jakarta 10340</p>
              </div>
            </div>
          </div>

          {/* Resepsi (Reception) */}
          <div
            class="details-card wedding-card bg-wedding-sage border-0 transition-all duration-300 hover:shadow-lg"
            style={{ opacity: 0 }}
          >
            <div class="text-center p-8">
              <div class="mb-4">
                <svg
                  class="w-12 h-12 mx-auto mb-4"
                  style={{ color: "var(--wedding-accent)" }}
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z"/>
                </svg>
              </div>

              <h3 class="font-serif text-3xl md:text-4xl text-wedding-brown mb-4 font-medium">
                Resepsi
              </h3>

              <div class="text-wedding-accent text-lg mb-4 italic">
                Resepsi & Perayaan Pernikahan
              </div>

              <div class="mb-6">
                <p class="text-wedding-text-secondary text-xl md:text-2xl font-medium mb-2">
                  12:00 PM - 3:00 PM
                </p>
                <p class="text-wedding-text-muted text-lg">
                  Sabtu, 29 November 2025
                </p>
              </div>

              <div class="text-wedding-text-muted text-base md:text-lg space-y-2 mb-6">
                <p class="font-medium">Tamarin Hotel Jakarta</p>
                <p>Jl. K.H. Wahid Hasyim No.77, RT.1/RW.4</p>
                <p>Gondangdia, Kec. Menteng, Jakarta 10340</p>
              </div>
            </div>
          </div>
        </div>

        {/* Additional Information */}
        <div class="mt-16 max-w-4xl mx-auto">
          <div
            class="details-card wedding-card bg-wedding-lavender p-8 rounded-lg"
            style={{ opacity: 0 }}
          >
            <h3 class="font-serif text-2xl md:text-3xl text-wedding-brown mb-6 text-center">
              Informasi Penting
            </h3>

            <div class="grid md:grid-cols-2 gap-8">
              <div>
                <h4 class="font-semibold text-wedding-brown mb-3">Parkir</h4>
                <p class="text-wedding-text-muted text-sm">
                  Area parkir tersedia di gedung Tamarin Hotel Jakarta untuk kenyamanan tamu.
                </p>
              </div>

              <div>
                <h4 class="font-semibold text-wedding-brown mb-3">Transportasi Umum</h4>
                <p class="text-wedding-text-muted text-sm">
                  <strong>MRT:</strong> Stasiun Bundaran HI (10 menit jalan kaki, 654m)
                  <br />
                  <strong>TransJakarta:</strong> Halte Sarinah (433m)
                  <br />
                  <strong>Bus:</strong> Jalur 1, 1H, 9D, AC52, JAK.10A
                  <br />
                  <strong>Kereta:</strong> Stasiun Gondangdia (6 menit jalan kaki)
                </p>
              </div>

              <div>
                <h4 class="font-semibold text-wedding-brown mb-3">Lokasi</h4>
                <p class="text-wedding-text-muted text-sm">
                  Hotel terletak di pusat kota Jakarta dengan akses mudah dari berbagai arah.
                  Area Menteng sangat terhubung dengan jaringan transportasi umum.
                </p>
              </div>

              <div>
                <h4 class="font-semibold text-wedding-brown mb-3">Akomodasi</h4>
                <p class="text-wedding-text-muted text-sm">
                  Untuk tamu luar kota, Tamarin Hotel Jakarta menyediakan kamar.
                  Hubungi kami untuk informasi lebih lanjut.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
});

// src/lib/components/DetailsSection.svelte
<section
	id="details"
	class="min-h-screen bg-gradient-to-b from-wedding-silver-light to-wedding-sky flex flex-col items-center justify-center px-4 py-20"
>
	<div class="max-w-6xl mx-auto text-center">
		<!-- Opening Greeting -->
		<div class="mb-16">
			<h2 class="font-serif text-3xl md:text-5xl text-wedding-navy mb-6 font-light">
				Assalamu'alaikum Wr. Wb
			</h2>
			<p class="text-lg md:text-xl text-wedding-text-dark max-w-3xl mx-auto">
				Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i serta kerabat sekalian
				untuk menghadiri acara pernikahan kami.
			</p>
		</div>

		<!-- Couple Information -->
		<div class="grid md:grid-cols-2 gap-x-12 gap-y-8 max-w-4xl mx-auto mb-16">
			<!-- Bride -->
			<div class="wedding-card bg-white p-8 rounded-lg shadow-md">
				<div class="mb-4">
					<div
						class="w-40 h-56 mx-auto mb-4 decorative-frame overflow-hidden flex items-center justify-center"
					>
						<img
							src="/photos/alfina-photo.jpg"
							alt="Alfina Nurmayati"
							class="w-full h-full object-cover"
						/>
					</div>
				</div>
				<h3 class="font-serif text-3xl md:text-4xl text-wedding-navy mb-4 font-medium">
					Alfina Nurmayati
				</h3>
				<p class="text-wedding-text-dark mb-6">
					Putri Pertama dari Bapak Muhanan<br />
					& Ibu Nurhayati
				</p>
				<a
					href="https://www.instagram.com/nurmaalfn/"
					target="_blank"
					rel="noopener noreferrer"
					class="inline-flex items-center gap-x-2 text-wedding-navy hover:text-wedding-navy transition-colors"
				>
					<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
						<path
							d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"
						/>
					</svg>
					<span>Instagram</span>
				</a>
			</div>

			<!-- Groom -->
			<div class="wedding-card bg-white p-8 rounded-lg shadow-md">
				<div class="mb-4">
					<div
						class="w-40 h-56 mx-auto mb-4 decorative-frame overflow-hidden flex items-center justify-center"
					>
						<img
							src="/photos/mugni-photo.jpg"
							alt="Muhammad Mugni Hadi"
							class="w-full h-full object-cover"
						/>
					</div>
				</div>
				<h3 class="font-serif text-3xl md:text-4xl text-wedding-navy mb-4 font-medium">
					Muhammad Mugni Hadi
				</h3>
				<p class="text-wedding-text-dark mb-6">
					Putra Ketiga dari Bapak Suaidi<br />
					& Ibu Anne Machdalia
				</p>
				<a
					href="https://www.instagram.com/mugnimaestra/"
					target="_blank"
					rel="noopener noreferrer"
					class="inline-flex items-center gap-x-2 text-wedding-navy hover:text-wedding-steel transition-colors"
				>
					<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
						<path
							d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"
						/>
					</svg>
					<span>Instagram</span>
				</a>
			</div>
		</div>

		<!-- Quranic Verse -->
		<div class="mb-16 max-w-3xl mx-auto">
			<h3 class="font-serif text-2xl md:text-3xl text-wedding-navy mb-4">Save The Date</h3>
			<p class="text-base md:text-lg italic text-wedding-text-dark mb-2">
				"Dan segala sesuatu Kami ciptakan berpasang-pasangan agar kamu mengingat (kebesaran Allah)."
			</p>
			<p class="text-sm text-wedding-text-muted">(QS. Az Zariyat: 49)</p>
		</div>

		<!-- Event Details -->
		<div class="grid md:grid-cols-2 gap-x-12 gap-y-8 max-w-5xl mx-auto">
			<!-- Akad Nikah -->
			<div
				class="wedding-card bg-wedding-navy text-white border-2 border-wedding-steel transition-all duration-300 hover:shadow-2xl hover:border-wedding-accent"
			>
				<div class="text-center p-8">
					<div class="mb-4">
						<svg
							class="w-12 h-12 mx-auto mb-4 text-wedding-sky"
							fill="currentColor"
							viewBox="0 0 20 20"
						>
							<path d="M10 2L3 7v11a2 2 0 002 2h4v-6h2v6h4a2 2 0 002-2V7l-7-5z" />
						</svg>
					</div>

					<h3 class="font-serif text-3xl md:text-4xl text-white mb-4 font-medium">Akad Nikah</h3>

					<div class="mb-6">
						<p class="text-wedding-sky text-lg mb-2">Sabtu, 29 November 2025</p>
						<p class="text-white text-xl md:text-2xl font-medium">Pukul : 09.00 WIB – Selesai</p>
					</div>

					<div class="text-wedding-sky text-base md:text-lg space-y-2 mb-6">
						<p class="font-medium">Tempat : Tamarin Hotel Jakarta</p>
						<p>Jl. K.H. Wahid Hasyim No.77, RT.1/RW.4</p>
						<p>Gondangdia, Kec. Menteng, Jakarta 10340</p>
					</div>

					<a
						href="https://maps.app.goo.gl/yrBPbUvREyhiqcmK6"
						target="_blank"
						rel="noopener noreferrer"
						class="inline-block wedding-button bg-wedding-sky text-wedding-navy hover:bg-white transition-all duration-300 shadow-md hover:shadow-lg px-6 py-2 rounded-full font-medium"
					>
						Lihat Lokasi
					</a>
				</div>
			</div>

			<!-- Resepsi (Reception) -->
			<div
				class="wedding-card bg-wedding-navy text-white border-2 border-wedding-steel transition-all duration-300 hover:shadow-2xl hover:border-wedding-accent"
			>
				<div class="text-center p-8">
					<div class="mb-4">
						<svg
							class="w-12 h-12 mx-auto mb-4 text-wedding-sky"
							fill="currentColor"
							viewBox="0 0 20 20"
						>
							<path
								d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z"
							/>
						</svg>
					</div>

					<h3 class="font-serif text-3xl md:text-4xl text-white mb-4 font-medium">Resepsi</h3>

					<div class="mb-6">
						<p class="text-wedding-sky text-lg mb-2">Sabtu, 29 November 2025</p>
						<p class="text-white text-xl md:text-2xl font-medium">Pukul : 12.00 WIB – Selesai</p>
					</div>

					<div class="text-wedding-sky text-base md:text-lg space-y-2 mb-6">
						<p class="font-medium">Tempat : Tamarin Hotel Jakarta</p>
						<p>Jl. K.H. Wahid Hasyim No.77, RT.1/RW.4</p>
						<p>Gondangdia, Kec. Menteng, Jakarta 10340</p>
					</div>

					<a
						href="https://maps.app.goo.gl/yrBPbUvREyhiqcmK6"
						target="_blank"
						rel="noopener noreferrer"
						class="inline-block wedding-button bg-wedding-sky text-wedding-navy hover:bg-white transition-all duration-300 shadow-md hover:shadow-lg px-6 py-2 rounded-full font-medium"
					>
						Lihat Lokasi
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

<style>
	.decorative-frame {
		--b: 3px; /* border thickness */
		--s: 16px; /* size of corner decoration */
		--c: #5d88bb; /* wedding-steel color */
		--c2: #102336; /* wedding-navy color */
		--c3: #b3cbe4; /* wedding-sky color */

		position: relative;
		border-radius: 50% / 40%; /* Portrait/oval shape: 50% horizontal, 40% vertical */
		background:
			/* Top-left corner */ conic-gradient(
					from 90deg at top var(--b) left var(--b),
					transparent 25%,
					var(--c) 0 50%,
					transparent 0
				)
				0 0,
			/* Top-right corner */
				conic-gradient(
					from 180deg at top var(--b) right var(--b),
					transparent 25%,
					var(--c) 0 50%,
					transparent 0
				)
				100% 0,
			/* Bottom-left corner */
				conic-gradient(
					from 0deg at bottom var(--b) left var(--b),
					transparent 25%,
					var(--c) 0 50%,
					transparent 0
				)
				0 100%,
			/* Bottom-right corner */
				conic-gradient(
					from -90deg at bottom var(--b) right var(--b),
					transparent 25%,
					var(--c) 0 50%,
					transparent 0
				)
				100% 100%,
			/* Base background - ellipse instead of circle */
				radial-gradient(ellipse at center, var(--c3) 0%, var(--c3) 100%);
		background-size: var(--s) var(--s), var(--s) var(--s), var(--s) var(--s), var(--s) var(--s),
			100% 100%;
		background-repeat: no-repeat;
		border: var(--b) solid var(--c);
		box-shadow: 0 0 0 2px var(--c2), 0 4px 12px rgba(16, 35, 54, 0.15),
			inset 0 0 0 1px rgba(93, 136, 187, 0.2);
	}

	.decorative-frame::before {
		content: '';
		position: absolute;
		inset: calc(var(--b) + 2px);
		border-radius: 50% / 40%; /* Match parent oval shape */
		border: 1px solid rgba(255, 255, 255, 0.4);
		pointer-events: none;
		z-index: 1;
	}

	.decorative-frame img {
		position: relative;
		z-index: 0;
		border-radius: 50% / 40%; /* Match parent oval shape */
		box-shadow: inset 0 0 8px rgba(0, 0, 0, 0.1);
	}
</style>
