// src/components/footer-section.tsx
import { component$ } from "@builder.io/qwik";

export const FooterSection = component$(() => {
  return (
    <footer class="bg-wedding-brown text-center px-4 py-16">
      <div class="max-w-4xl mx-auto">
        <h2 class="font-serif text-2xl md:text-3xl text-wedding-cream mb-6 font-light">
          Thank you for being part of our special day
        </h2>

        <div class="text-wedding-cream opacity-80 mb-6">
          <p class="text-lg md:text-xl mb-2 font-medium">With love,</p>
          <p class="text-lg md:text-xl">Alfina & Mugni</p>
        </div>

        <div class="text-wedding-cream opacity-60 text-sm md:text-base">
          November 29, 2025 • Jakarta, Indonesia
        </div>

        <div class="mt-12 pt-8 border-t border-wedding-cream border-opacity-20">
          <p class="text-wedding-cream opacity-50 text-sm">
            Made with ❤️ for our special day
          </p>
        </div>
      </div>
    </footer>
  );
});

// src/lib/components/FooterSection.svelte
<section class="bg-gradient-to-b from-wedding-silver-light to-wedding-navy py-20">
	<div class="max-w-4xl mx-auto px-4 text-center">
		<!-- Closing Greeting -->
		<div class="mb-8">
			<h3 class="text-2xl md:text-3xl font-serif font-light text-wedding-silver-light mb-4">
				Salam Hangat
			</h3>
			<p class="text-xl md:text-2xl font-serif font-medium text-wedding-silver-light">
				Alfina & Mugni
			</p>
		</div>
	</div>
</section>
